### ISSUE TITLE
Weird layer at the top of image_view for rgb images

### ISSUE THREAD

**Issue by rajk97** [microsoft/Azure_Kinect_ROS_Driver#104]
Hi all, 

Lately, when I'm trying to run image_view to visualize /rgb/image_raw, I'm getting a weird filter at the top that looks like below:

![image](https://user-images.githubusercontent.com/32988799/70286637-f4a34f80-1799-11ea-8876-4c10d90457f9.png)

Any idea why this might be happening? Kindly suggest. Thank you.

**Comment by ooeygui** [comment]
This appears to be a rendering artifact, not a camera artifact. Can you attempt to view with the camera directly using the Kinect SDK?

**Comment by rajk97** [comment]
Thanks for your reply. I did try it with Kinect SDK and it didn't have a problem with it. Any idea of how we can fix this? Please comment. Thanks.

**Comment by ooeygui** [comment]
@rajk97 This appears to be a rendering problem on your system - not a camera or Kinect ROS node problem.
