### ISSUE TITLE
Body tracking latency

### ISSUE THREAD

**Issue by pengy8** [microsoft/Azure_Kinect_ROS_Driver#109]
**Is your feature request related to a problem? Please describe.**
The body tracking data in the ROS driver is very useful to my application, but somehow there's about 1-second latency in the reported data. However, the data seen in the body tracking SDK is faster (about 0.25 second). 

**Describe the solution you'd like**
Is there any way to improve the body tracking data latency in the ROS driver to be close to the SDK's speed?

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ooeygui** [comment]
It may be due to the double hop though pub/sub.

**Comment by RoseFlunder** [comment]
There is also a huge discussion when it comes to the latency about the body tracking sdk in the sdk repository:
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/514

I am on mobile at the moment but I remember that one person wrote that there is like 1 buffered frame in the body tracker after creation. He got less latency when he pulled that from the body tracker instance before queing new frames. Maybe you can test this.

**Comment by ooeygui** [comment]
@RoseFlunder Thank you for linking this in.
