### ISSUE TITLE
Launch camera false when run command ssh on different PC 

### ISSUE THREAD

**Issue by tuan97anton** [microsoft/Azure_Kinect_ROS_Driver#117]
### Describe the bug

- I have 2 PC Linux ( Ubuntu 18, ROS Melodic ). PC 1 ( I58200, ram 16GB ) connects directly with camera Azure kinect , PC 2 ( my laptop ) connect to PC 1 through SSH . 

- I run cmt : `roslaunch azure_kinect_ros_driver driver.launch`

- If I run cmt above on PC 1 , It work . But I run cmt above on PC 2 ( my laptop )  connect to PC 1 through SSH, It error : Failed to start cameras

### On PC1 : 

SUMMARY
========

PARAMETERS
 * /azure_kinect_ros_driver/body_tracking_enabled: False
 * /azure_kinect_ros_driver/body_tracking_smoothing_factor: 0.0
 * /azure_kinect_ros_driver/color_enabled: True
 * /azure_kinect_ros_driver/color_format: bgra
 * /azure_kinect_ros_driver/color_resolution: 720P
 * /azure_kinect_ros_driver/depth_enabled: True
 * /azure_kinect_ros_driver/depth_mode: WFOV_UNBINNED
 * /azure_kinect_ros_driver/fps: 5
 * /azure_kinect_ros_driver/imu_rate_target: 0
 * /azure_kinect_ros_driver/ir_mono8_scaling_factor: 1.0
 * /azure_kinect_ros_driver/point_cloud: True
 * /azure_kinect_ros_driver/point_cloud_in_depth_frame: False
 * /azure_kinect_ros_driver/recording_file: 
 * /azure_kinect_ros_driver/recording_loop_enabled: False
 * /azure_kinect_ros_driver/rescale_ir_to_mono8: False
 * /azure_kinect_ros_driver/rgb_point_cloud: True
 * /azure_kinect_ros_driver/sensor_sn: 
 * /azure_kinect_ros_driver/subordinate_delay_off_master_usec: 0
 * /azure_kinect_ros_driver/tf_prefix: 
 * /azure_kinect_ros_driver/wired_sync_mode: 0
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    azure_kinect_ros_driver (azure_kinect_ros_driver/node)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)

auto-starting new master
process[master]: started with pid [14338]
ROS_MASTER_URI=http://192.168.1.4:11311

setting /run_id to 72725fb4-592b-11ea-8ea1-04ea56e5db11
process[rosout-1]: started with pid [14349]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [14356]
process[robot_state_publisher-3]: started with pid [14357]
process[azure_kinect_ros_driver-4]: started with pid [14358]
[ WARN] [1582785373.630906633]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
[ INFO] [1582785373.714381596]: K4A Parameters:
[ INFO] [1582785373.714919571]: sensor_sn - std::string : 
[ INFO] [1582785373.714963715]: depth_enabled - bool : 1
[ INFO] [1582785373.714982461]: depth_mode - std::string : WFOV_UNBINNED
[ INFO] [1582785373.715013803]: color_enabled - bool : 1
[ INFO] [1582785373.715046843]: color_format - std::string : bgra
[ INFO] [1582785373.715062646]: color_resolution - std::string : 720P
[ INFO] [1582785373.715109958]: fps - int : 5
[ INFO] [1582785373.715126957]: point_cloud - bool : 1
[ INFO] [1582785373.715144418]: rgb_point_cloud - bool : 1
[ INFO] [1582785373.715159458]: point_cloud_in_depth_frame - bool : 0
[ INFO] [1582785373.715173636]: tf_prefix - std::string : 
[ INFO] [1582785373.715187926]: recording_file - std::string : 
[ INFO] [1582785373.715202251]: recording_loop_enabled - bool : 0
[ INFO] [1582785373.715216804]: body_tracking_enabled - bool : 0
[ INFO] [1582785373.715244183]: body_tracking_smoothing_factor - float : 0
[ INFO] [1582785373.715258873]: imu_rate_target - int : 0
[ INFO] [1582785373.715273422]: rescale_ir_to_mono8 - bool : 0
[ INFO] [1582785373.715290076]: ir_mono8_scaling_factor - float : 1
[ INFO] [1582785373.715304825]: wired_sync_mode - int : 0
[ INFO] [1582785373.715319654]: subordinate_delay_off_master_usec - int : 0
[ INFO] [1582785373.718311875]: Found 1 sensors
[ INFO] [1582785373.718358968]: No serial number provided: picking first sensor
[ INFO] [1582785373.949893019]: K4A[0] : 001456594512
[ INFO] [1582785374.000452352]: K4A Serial Number: 001456594512
[ INFO] [1582785374.005921447]: RGB Version: 1.6.102
[ INFO] [1582785374.005968828]: Depth Version: 1.6.75
[ INFO] [1582785374.005990333]: Audio Version: 1.6.14
[ INFO] [1582785374.006013613]: Depth Sensor Version: 6109.7.0
[ INFO] [1582785374.107727277]: Setting wired sync mode: 0
[ INFO] [1582785374.107776362]: Setting subordinate delay: 0
[ INFO] [1582785374.107822841]: Setting RGB Camera Format: bgra
[ INFO] [1582785374.107857409]: Setting RGB Camera Resolution: 720P
[ INFO] [1582785374.107896296]: Setting Depth Camera Mode: WFOV_UNBINNED
[ INFO] [1582785374.107930729]: Setting Camera FPS: 5
[ INFO] [1582785374.107970515]: Using default IMU rate. Setting to maximum: 1600 Hz.
[ INFO] [1582785374.108026262]: Setting Target IMU rate to 1600 (desired: 1600)
[ INFO] [1582785374.443369682]: K4A Calibration Blob:
[ INFO] [1582785374.443413962]:          Depth:
[ INFO] [1582785374.443441739]:                  Extrinsics:
[ INFO] [1582785374.443468226]:                          Translation: 0, 0, 0
[ INFO] [1582785374.443491423]:                          Rotation[0]: 1, 0, 0
[ INFO] [1582785374.443513453]:                          Rotation[1]: 0, 1, 0
[ INFO] [1582785374.443536658]:                          Rotation[2]: 0, 0, 1
[ INFO] [1582785374.443556090]:                  Resolution:
[ INFO] [1582785374.443575869]:                          Width: 1024
[ INFO] [1582785374.443595764]:                          Height: 1024
[ INFO] [1582785374.443612966]:                  Intrinsics:
[ INFO] [1582785374.443632619]:                          Model Type: 4
[ INFO] [1582785374.443651689]:                          Parameter Count: 14
[ INFO] [1582785374.443672111]:                          cx: 515.193
[ INFO] [1582785374.443692550]:                          cy: 513.969
[ INFO] [1582785374.443712523]:                          fx: 504.038
[ INFO] [1582785374.443731982]:                          fy: 504.114
[ INFO] [1582785374.443751910]:                          k1: 8.35586
[ INFO] [1582785374.443774171]:                          k2: 5.64104
[ INFO] [1582785374.443793018]:                          k3: 0.291409
[ INFO] [1582785374.443814586]:                          k4: 8.67955
[ INFO] [1582785374.443834733]:                          k5: 8.46396
[ INFO] [1582785374.443853867]:                          k6: 1.53287
[ INFO] [1582785374.443873007]:                          codx: 0
[ INFO] [1582785374.443894068]:                          cody: 0
[ INFO] [1582785374.443913879]:                          p2: 3.05543e-05
[ INFO] [1582785374.443934132]:                          p1: -6.42042e-05
[ INFO] [1582785374.443954231]:                          metric_radius: 0
[ INFO] [1582785374.443972812]:          Color:
[ INFO] [1582785374.443988802]:                  Extrinsics:
[ INFO] [1582785374.444010524]:                          Translation: -32.0416, -1.97825, 3.9338
[ INFO] [1582785374.444031017]:                          Rotation[0]: 0.999997, 0.000882098, -0.00244055
[ INFO] [1582785374.444053412]:                          Rotation[1]: -0.000658686, 0.995935, 0.0900734
[ INFO] [1582785374.444074418]:                          Rotation[2]: 0.00251008, -0.0900715, 0.995932
[ INFO] [1582785374.444091686]:                  Resolution:
[ INFO] [1582785374.444109358]:                          Width: 1280
[ INFO] [1582785374.444127237]:                          Height: 720
[ INFO] [1582785374.444143332]:                  Intrinsics:
[ INFO] [1582785374.444163438]:                          Model Type: 4
[ INFO] [1582785374.444186539]:                          Parameter Count: 14
[ INFO] [1582785374.444209514]:                          cx: 638.009
[ INFO] [1582785374.444228404]:                          cy: 370.245
[ INFO] [1582785374.444248137]:                          fx: 611.877
[ INFO] [1582785374.444269590]:                          fy: 611.842
[ INFO] [1582785374.444287609]:                          k1: 0.695646
[ INFO] [1582785374.444309756]:                          k2: -2.85069
[ INFO] [1582785374.444328982]:                          k3: 1.58158
[ INFO] [1582785374.444347542]:                          k4: 0.571472
[ INFO] [1582785374.444365756]:                          k5: -2.67611
[ INFO] [1582785374.444384454]:                          k6: 1.51184
[ INFO] [1582785374.444405293]:                          codx: 0
[ INFO] [1582785374.444422964]:                          cody: 0
[ INFO] [1582785374.444441726]:                          p2: -0.000394091
[ INFO] [1582785374.444460389]:                          p1: 0.000928221
[ INFO] [1582785374.444478291]:                          metric_radius: 0
[ INFO] [1582785374.444497280]:          IMU (Depth to Color):
[ INFO] [1582785374.444513287]:                  Extrinsics:
[ INFO] [1582785374.444533540]:                          Translation: -32.0416, -1.97825, 3.9338
[ INFO] [1582785374.444556305]:                          Rotation[0]: 0.999997, 0.000882098, -0.00244055
[ INFO] [1582785374.444576394]:                          Rotation[1]: -0.000658686, 0.995935, 0.0900734
[ INFO] [1582785374.444596710]:                          Rotation[2]: 0.00251008, -0.0900715, 0.995932
[ INFO] [1582785374.444614512]:          IMU (Depth to IMU):
[ INFO] [1582785374.444630100]:                  Extrinsics:
[ INFO] [1582785374.444651519]:                          Translation: -51.0044, 3.32636, 1.56929
[ INFO] [1582785374.444671105]:                          Rotation[0]: -0.000252766, 0.11015, -0.993915
[ INFO] [1582785374.444692350]:                          Rotation[1]: -1, -0.000332787, 0.000217433
[ INFO] [1582785374.444711715]:                          Rotation[2]: -0.000306812, 0.993915, 0.11015
[ INFO] [1582785374.444730279]:          IMU (IMU to Depth):
[ INFO] [1582785374.444746264]:                  Extrinsics:
[ INFO] [1582785374.444768481]:                          Translation: 3.31395, 4.05948, -50.8677
[ INFO] [1582785374.444790936]:                          Rotation[0]: -0.000252766, -1, -0.000306812
[ INFO] [1582785374.444816543]:                          Rotation[1]: 0.11015, -0.000332787, 0.993915
[ INFO] [1582785374.444839853]:                          Rotation[2]: -0.993915, 0.000217433, 0.11015
[ INFO] [1582785374.444860310]:          IMU (Color to IMU):
[ INFO] [1582785374.444875383]:                  Extrinsics:
[ INFO] [1582785374.444893856]:                          Translation: -46.9588, -28.7056, 3.47741
[ INFO] [1582785374.444912368]:                          Rotation[0]: 0.0022701, 0.0201766, -0.999794
[ INFO] [1582785374.444930292]:                          Rotation[1]: -0.999997, 0.000346836, -0.00226356
[ INFO] [1582785374.444950320]:                          Rotation[2]: 0.000301093, 0.999796, 0.0201774
[ INFO] [1582785374.444967287]:          IMU (IMU to Color):
[ INFO] [1582785374.444980868]:                  Extrinsics:
[ INFO] [1582785374.445003637]:                          Translation: -28.6, -2.51928, -47.0843
[ INFO] [1582785374.445021465]:                          Rotation[0]: 0.0022701, -0.999997, 0.000301093
[ INFO] [1582785374.445038949]:                          Rotation[1]: 0.0201766, 0.000346836, 0.999796
[ INFO] [1582785374.445057993]:                          Rotation[2]: -0.999794, -0.00226356, 0.0201774
[ INFO] [1582785374.445132626]: STARTING CAMERAS
[ INFO] [1582785375.044141068]: STARTING IMU
[ INFO] [1582785375.045231615]: K4A Started
[ WARN] [1582785375.245371889]: Initializing the device to realtime offset based on wall clock: 1582785375244912144 ns
[ WARN] [1582785375.892911148]: Initializing or re-initializing the device to realtime offset: 1582785375291026518 ns
[ WARN] [1582785376.100667711]: Image processing thread is running behind.
Expected max loop time: 0.200000000
Actual loop time: 0.848858541

### On PC 2 ( error : Failed to start cameras )

SUMMARY
========

PARAMETERS
 * /azure_kinect_ros_driver/body_tracking_enabled: False
 * /azure_kinect_ros_driver/body_tracking_smoothing_factor: 0.0
 * /azure_kinect_ros_driver/color_enabled: True
 * /azure_kinect_ros_driver/color_format: bgra
 * /azure_kinect_ros_driver/color_resolution: 720P
 * /azure_kinect_ros_driver/depth_enabled: True
 * /azure_kinect_ros_driver/depth_mode: WFOV_UNBINNED
 * /azure_kinect_ros_driver/fps: 5
 * /azure_kinect_ros_driver/imu_rate_target: 0
 * /azure_kinect_ros_driver/ir_mono8_scaling_factor: 1.0
 * /azure_kinect_ros_driver/point_cloud: True
 * /azure_kinect_ros_driver/point_cloud_in_depth_frame: False
 * /azure_kinect_ros_driver/recording_file: 
 * /azure_kinect_ros_driver/recording_loop_enabled: False
 * /azure_kinect_ros_driver/rescale_ir_to_mono8: False
 * /azure_kinect_ros_driver/rgb_point_cloud: True
 * /azure_kinect_ros_driver/sensor_sn: 
 * /azure_kinect_ros_driver/subordinate_delay_off_master_usec: 0
 * /azure_kinect_ros_driver/tf_prefix: 
 * /azure_kinect_ros_driver/wired_sync_mode: 0
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    azure_kinect_ros_driver (azure_kinect_ros_driver/node)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)

auto-starting new master
process[master]: started with pid [14532]
ROS_MASTER_URI=http://192.168.1.4:11311

setting /run_id to c229d42e-592b-11ea-8ea1-04ea56e5db11
process[rosout-1]: started with pid [14543]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [14547]
process[robot_state_publisher-3]: started with pid [14551]
process[azure_kinect_ros_driver-4]: started with pid [14552]
[ WARN] [1582785507.352598973]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
[ INFO] [1582785507.446514929]: K4A Parameters:
[ INFO] [1582785507.447087817]: sensor_sn - std::string : 
[ INFO] [1582785507.447109590]: depth_enabled - bool : 1
[ INFO] [1582785507.447128437]: depth_mode - std::string : WFOV_UNBINNED
[ INFO] [1582785507.447147594]: color_enabled - bool : 1
[ INFO] [1582785507.447165313]: color_format - std::string : bgra
[ INFO] [1582785507.447184475]: color_resolution - std::string : 720P
[ INFO] [1582785507.447200550]: fps - int : 5
[ INFO] [1582785507.447220143]: point_cloud - bool : 1
[ INFO] [1582785507.447237097]: rgb_point_cloud - bool : 1
[ INFO] [1582785507.447256719]: point_cloud_in_depth_frame - bool : 0
[ INFO] [1582785507.447273202]: tf_prefix - std::string : 
[ INFO] [1582785507.447291838]: recording_file - std::string : 
[ INFO] [1582785507.447308888]: recording_loop_enabled - bool : 0
[ INFO] [1582785507.447326701]: body_tracking_enabled - bool : 0
[ INFO] [1582785507.447359781]: body_tracking_smoothing_factor - float : 0
[ INFO] [1582785507.447375869]: imu_rate_target - int : 0
[ INFO] [1582785507.447395264]: rescale_ir_to_mono8 - bool : 0
[ INFO] [1582785507.447414576]: ir_mono8_scaling_factor - float : 1
[ INFO] [1582785507.447433811]: wired_sync_mode - int : 0
[ INFO] [1582785507.447452053]: subordinate_delay_off_master_usec - int : 0
[ INFO] [1582785507.450198461]: Found 1 sensors
[ INFO] [1582785507.450239438]: No serial number provided: picking first sensor
[ INFO] [1582785507.714260656]: K4A[0] : 001456594512
[ INFO] [1582785507.764790431]: K4A Serial Number: 001456594512
[ INFO] [1582785507.770339498]: RGB Version: 1.6.102
[ INFO] [1582785507.770409700]: Depth Version: 1.6.75
[ INFO] [1582785507.770458024]: Audio Version: 1.6.14
[ INFO] [1582785507.770493714]: Depth Sensor Version: 6109.7.0
[ INFO] [1582785507.890291629]: Setting wired sync mode: 0
[ INFO] [1582785507.890343574]: Setting subordinate delay: 0
[ INFO] [1582785507.890386404]: Setting RGB Camera Format: bgra
[ INFO] [1582785507.890438776]: Setting RGB Camera Resolution: 720P
[ INFO] [1582785507.890459772]: Setting Depth Camera Mode: WFOV_UNBINNED
[ INFO] [1582785507.890513961]: Setting Camera FPS: 5
[ INFO] [1582785507.890534368]: Using default IMU rate. Setting to maximum: 1600 Hz.
[ INFO] [1582785507.890556384]: Setting Target IMU rate to 1600 (desired: 1600)
[2020-02-27 13:38:28.195] [error] [t=14587] ../src/tewrapper/tewrapper.c (61): transform_engine_start_helper(). Transform engine create and initialize failed with error code: 204.
[2020-02-27 13:38:28.195] [error] [t=14587] ../src/tewrapper/tewrapper.c (68): teresult == K4A_DEPTH_ENGINE_RESULT_SUCCEEDED returned failure in transform_engine_start_helper()
[2020-02-27 13:38:28.195] [error] [t=14587] ../src/tewrapper/tewrapper.c (86): transform_engine_start_helper(tewrapper) returned failure in transform_engine_thread()
[2020-02-27 13:38:28.195] [error] [t=14552] ../src/tewrapper/tewrapper.c (313): tewrapper_create(). Transform Engine thread failed to start
[2020-02-27 13:38:28.195] [error] [t=14552] ../src/transformation/transformation.c (637): transformation_context->tewrapper != NULL returned failure in transformation_create()
[ INFO] [1582785508.195791416]: K4A Calibration Blob:
[ INFO] [1582785508.195825432]: 	 Depth:
[ INFO] [1582785508.195861350]: 		 Extrinsics:
[ INFO] [1582785508.195928463]: 			 Translation: 0, 0, 0
[ INFO] [1582785508.195994129]: 			 Rotation[0]: 1, 0, 0
[ INFO] [1582785508.196015938]: 			 Rotation[1]: 0, 1, 0
[ INFO] [1582785508.196049705]: 			 Rotation[2]: 0, 0, 1
[ INFO] [1582785508.196088622]: 		 Resolution:
[ INFO] [1582785508.196139489]: 			 Width: 1024
[ INFO] [1582785508.196189386]: 			 Height: 1024
[ INFO] [1582785508.196209826]: 		 Intrinsics:
[ INFO] [1582785508.196230275]: 			 Model Type: 4
[ INFO] [1582785508.196249874]: 			 Parameter Count: 14
[ INFO] [1582785508.196285421]: 			 cx: 515.193
[ INFO] [1582785508.196324486]: 			 cy: 513.969
[ INFO] [1582785508.196346031]: 			 fx: 504.038
[ INFO] [1582785508.196379559]: 			 fy: 504.114
[ INFO] [1582785508.196418175]: 			 k1: 8.35586
[ INFO] [1582785508.196439576]: 			 k2: 5.64104
[ INFO] [1582785508.196473065]: 			 k3: 0.291409
[ INFO] [1582785508.196513027]: 			 k4: 8.67955
[ INFO] [1582785508.196532040]: 			 k5: 8.46396
[ INFO] [1582785508.196550596]: 			 k6: 1.53287
[ INFO] [1582785508.196573368]: 			 codx: 0
[ INFO] [1582785508.196591401]: 			 cody: 0
[ INFO] [1582785508.196613433]: 			 p2: 3.05543e-05
[ INFO] [1582785508.196632687]: 			 p1: -6.42042e-05
[ INFO] [1582785508.196654656]: 			 metric_radius: 0
[ INFO] [1582785508.196672904]: 	 Color:
[ INFO] [1582785508.196688458]: 		 Extrinsics:
[ INFO] [1582785508.196711024]: 			 Translation: -32.0416, -1.97825, 3.9338
[ INFO] [1582785508.196732886]: 			 Rotation[0]: 0.999997, 0.000882098, -0.00244055
[ INFO] [1582785508.196753677]: 			 Rotation[1]: -0.000658686, 0.995935, 0.0900734
[ INFO] [1582785508.196776062]: 			 Rotation[2]: 0.00251008, -0.0900715, 0.995932
[ INFO] [1582785508.196791687]: 		 Resolution:
[ INFO] [1582785508.196808967]: 			 Width: 1280
[ INFO] [1582785508.196825818]: 			 Height: 720
[ INFO] [1582785508.196842114]: 		 Intrinsics:
[ INFO] [1582785508.196865462]: 			 Model Type: 4
[ INFO] [1582785508.196884341]: 			 Parameter Count: 14
[ INFO] [1582785508.196905779]: 			 cx: 638.009
[ INFO] [1582785508.196923884]: 			 cy: 370.245
[ INFO] [1582785508.196944953]: 			 fx: 611.877
[ INFO] [1582785508.196963237]: 			 fy: 611.842
[ INFO] [1582785508.196981086]: 			 k1: 0.695646
[ INFO] [1582785508.197000110]: 			 k2: -2.85069
[ INFO] [1582785508.197021579]: 			 k3: 1.58158
[ INFO] [1582785508.197040637]: 			 k4: 0.571472
[ INFO] [1582785508.197061591]: 			 k5: -2.67611
[ INFO] [1582785508.197079681]: 			 k6: 1.51184
[ INFO] [1582785508.197098112]: 			 codx: 0
[ INFO] [1582785508.197118024]: 			 cody: 0
[ INFO] [1582785508.197136870]: 			 p2: -0.000394091
[ INFO] [1582785508.197155245]: 			 p1: 0.000928221
[ INFO] [1582785508.197172816]: 			 metric_radius: 0
[ INFO] [1582785508.197194852]: 	 IMU (Depth to Color):
[ INFO] [1582785508.197210805]: 		 Extrinsics:
[ INFO] [1582785508.197232373]: 			 Translation: -32.0416, -1.97825, 3.9338
[ INFO] [1582785508.197252102]: 			 Rotation[0]: 0.999997, 0.000882098, -0.00244055
[ INFO] [1582785508.197271844]: 			 Rotation[1]: -0.000658686, 0.995935, 0.0900734
[ INFO] [1582785508.197291426]: 			 Rotation[2]: 0.00251008, -0.0900715, 0.995932
[ INFO] [1582785508.197310577]: 	 IMU (Depth to IMU):
[ INFO] [1582785508.197327933]: 		 Extrinsics:
[ INFO] [1582785508.197349885]: 			 Translation: -51.0044, 3.32636, 1.56929
[ INFO] [1582785508.197368856]: 			 Rotation[0]: -0.000252766, 0.11015, -0.993915
[ INFO] [1582785508.197388469]: 			 Rotation[1]: -1, -0.000332787, 0.000217433
[ INFO] [1582785508.197407261]: 			 Rotation[2]: -0.000306812, 0.993915, 0.11015
[ INFO] [1582785508.197427710]: 	 IMU (IMU to Depth):
[ INFO] [1582785508.197444189]: 		 Extrinsics:
[ INFO] [1582785508.197464873]: 			 Translation: 3.31395, 4.05948, -50.8677
[ INFO] [1582785508.197484110]: 			 Rotation[0]: -0.000252766, -1, -0.000306812
[ INFO] [1582785508.197502849]: 			 Rotation[1]: 0.11015, -0.000332787, 0.993915
[ INFO] [1582785508.197553596]: 			 Rotation[2]: -0.993915, 0.000217433, 0.11015
[ INFO] [1582785508.197571542]: 	 IMU (Color to IMU):
[ INFO] [1582785508.197586701]: 		 Extrinsics:
[ INFO] [1582785508.197611124]: 			 Translation: -46.9588, -28.7056, 3.47741
[ INFO] [1582785508.197630135]: 			 Rotation[0]: 0.0022701, 0.0201766, -0.999794
[ INFO] [1582785508.197651059]: 			 Rotation[1]: -0.999997, 0.000346836, -0.00226356
[ INFO] [1582785508.197670980]: 			 Rotation[2]: 0.000301093, 0.999796, 0.0201774
[ INFO] [1582785508.197690006]: 	 IMU (IMU to Color):
[ INFO] [1582785508.197705242]: 		 Extrinsics:
[ INFO] [1582785508.197726276]: 			 Translation: -28.6, -2.51928, -47.0843
[ INFO] [1582785508.197745173]: 			 Rotation[0]: 0.0022701, -0.999997, 0.000301093
[ INFO] [1582785508.197764460]: 			 Rotation[1]: 0.0201766, 0.000346836, 0.999796
[ INFO] [1582785508.197786015]: 			 Rotation[2]: -0.999794, -0.00226356, 0.0201774
[ INFO] [1582785508.197856434]: STARTING CAMERAS
[2020-02-27 13:38:28.478] [error] [t=14589] ../src/dewrapper/dewrapper.c (154): depth_engine_start_helper(). Depth engine create and initialize failed with error code: 204.
[2020-02-27 13:38:28.478] [error] [t=14589] ../src/dewrapper/dewrapper.c (160): deresult == K4A_DEPTH_ENGINE_RESULT_SUCCEEDED returned failure in depth_engine_start_helper()
[2020-02-27 13:38:28.478] [error] [t=14589] ../src/dewrapper/dewrapper.c (194): depth_engine_start_helper(dewrapper, dewrapper->fps, dewrapper->depth_mode, &depth_engine_max_compute_time_ms, &depth_engine_output_buffer_size) returned failure in depth_engine_thread()
[2020-02-27 13:38:28.478] [error] [t=14552] ../src/dewrapper/dewrapper.c (552): dewrapper_start(). Depth Engine thread failed to start
[2020-02-27 13:38:28.478] [error] [t=14552] ../src/depth/depth.c (398): dewrapper_start(depth->dewrapper, config, depth->calibration_memory, depth->calibration_memory_size) returned failure in depth_start()
[2020-02-27 13:38:28.479] [error] [t=14552] ../src/depth_mcu/depth_mcu.c (359): cmd_status == CMD_STATUS_PASS returned failure in depthmcu_depth_stop_streaming()
[2020-02-27 13:38:28.479] [error] [t=14552] ../src/depth_mcu/depth_mcu.c (362): depthmcu_depth_stop_streaming(). ERROR: cmd_status=0x00000063
[2020-02-27 13:38:28.479] [error] [t=14552] ../src/sdk/k4a.c (895): depth_start(device->depth, config) returned failure in k4a_device_start_cameras()
terminate called after throwing an instance of 'k4a::error'
  what():  Failed to start cameras!
[azure_kinect_ros_driver-4] process has died [pid 14552, exit code -6, cmd /home/sti/catkin_ws/devel/lib/azure_kinect_ros_driver/node __name:=azure_kinect_ros_driver __log:=/home/sti/.ros/log/c229d42e-592b-11ea-8ea1-04ea56e5db11/azure_kinect_ros_driver-4.log].
log file: /home/sti/.ros/log/c229d42e-592b-11ea-8ea1-04ea56e5db11/azure_kinect_ros_driver-4*.log

**I hope gives for your support . Thank you very much !!**

**Comment by RoseFlunder** [comment]
Try setting the "DISPLAY" environment variable after connecting via ssh.
Before running roslauch execute:
export DISPLAY=:0

**Comment by tuan97anton** [comment]
> Try setting the "DISPLAY" environment variable after connecting via ssh.
> Before running roslauch execute:
> export DISPLAY=:0

I tried and It work. Thank you very much ! :))

**Comment by tuan97anton** [comment]
I'm sorry . I still cannot start the Azure kinect camera via SSH (the error code is still as I said above). Although, I have added export DISPLAY=:0 in ~ / .bashrc. My camera is connected to the PC on the Robot and it does not have a screen. But , when i connected PC with a screen , I can again start camera via SSH .

**Comment by RoseFlunder** [comment]
As far as I know the bashrc environment variables will not be set when connecting via ssh.
Try to set the display variable explicitly after connecting via ssh with the export command.

**Comment by tuan97anton** [comment]
I tried : `export DISPLAY=:0` , and I check : `echo $DISPLAY` ( result :0 ) . But I run : `roslaunch azure_kinect_ros_driver driver.launch` . It don't work , the error code is still as I said above .

`[2020-03-12 11:26:05.264] [error] [t=3220] ../src/dewrapper/dewrapper.c (154): depth_engine_start_helper(). Depth engine create and initialize failed with error code: 204.
[2020-03-12 11:26:05.264] [error] [t=3220] ../src/dewrapper/dewrapper.c (160): deresult == K4A_DEPTH_ENGINE_RESULT_SUCCEEDED returned failure in depth_engine_start_helper()
[2020-03-12 11:26:05.264] [error] [t=3220] ../src/dewrapper/dewrapper.c (194): depth_engine_start_helper(dewrapper, dewrapper->fps, dewrapper->depth_mode, &depth_engine_max_compute_time_ms, &depth_engine_output_buffer_size) returned failure in depth_engine_thread()
[2020-03-12 11:26:05.264] [error] [t=3188] ../src/dewrapper/dewrapper.c (552): dewrapper_start(). Depth Engine thread failed to start
[2020-03-12 11:26:05.264] [error] [t=3188] ../src/depth/depth.c (398): dewrapper_start(depth->dewrapper, config, depth->calibration_memory, depth->calibration_memory_size) returned failure in depth_start()
[2020-03-12 11:26:05.264] [error] [t=3188] ../src/depth_mcu/depth_mcu.c (359): cmd_status == CMD_STATUS_PASS returned failure in depthmcu_depth_stop_streaming()
[2020-03-12 11:26:05.264] [error] [t=3188] ../src/depth_mcu/depth_mcu.c (362): depthmcu_depth_stop_streaming(). ERROR: cmd_status=0x00000063
[2020-03-12 11:26:05.264] [error] [t=3188] ../src/sdk/k4a.c (895): depth_start(device->depth, config) returned failure in k4a_device_start_cameras()
terminate called after throwing an instance of 'k4a::error'
  what():  Failed to start cameras!
`

**Comment by RoseFlunder** [comment]
Could you check the value of the display variable when the screen is connected?

**Comment by tuan97anton** [comment]
yes. Icheck :  echo $DISPLAY  -->result :0

**Comment by tuan97anton** [comment]
@RoseFlunder 
Thank your support ! I found my issues . After I turn on `automatic login` on ubuntu and `export DISPLAY=:0` , I can start camera via SSH .

**Comment by RoseFlunder** [comment]
Thanks for your feedback.
That makes sense. I was trying to reproduce it but I already had automatic login enabled so I didn't ran into this issue.
The X-Server is needed for open gl and will be started at login I think.

**Comment by abc619539082** [comment]
Hi . I have met a similar problem.
I tried to roslaunch on a PC (ubuntu18.04 ros-melodic but no gui)without a screen through SSH. And I met the same bug.
I turn on automatic login but it doesn't make sense.
Maybe it is impossible for driver.launch to run on a PC without a screen or gui?
Thank you!
