### ISSUE TITLE
Unable to launch multiple cameras in custom order

### ISSUE THREAD

**Issue by carcormir** [microsoft/Azure_Kinect_ROS_Driver#124]
**Describe the bug**
I have multiple cameras (6) connected to one PC. I am only able to launch without any errors when I launch the cameras in the same order that k4viewer shows them on the list of devices section.

Let's say I have 2 cameras showing with this order on k4aviewer:
sensor_sn = 0000000 (camera 1)
sensor_sn = 11111111 (camera 2)

If I launch the ROS driver of camera 2 and then of camera 1 it crashes. I can see in the source code (k4a_ros_decive.cpp) that it opens the devices in the order shown in the k4aviewer instead of using the provided sensor_sn.

Is there a way to open multiple devices in a different order than the one given by k4aviewer?
I would like to open a device given a sensor_sn.
Thanks in advance for the help!

OS: Ubuntu 18.04
ROS: Melodic
sdk: 1.3v

**Comment by ooeygui** [comment]
Thank you for the report. I'm duplicating to the *official support* task so we can combine the workstream.
https://github.com/microsoft/Azure_Kinect_ROS_Driver/issues/126
