### ISSUE TITLE
opencv version issue

### ISSUE THREAD

**Issue by bgyooPtr** [microsoft/Azure_Kinect_ROS_Driver#127]
ROS melodic's cv_bridge library uses the opencv 3.2 version.
However, when I build Kinect Azure with opencv 3.2, I get the following error.

> CMakeFiles/azure_kinect_ros_driver_node.dir/src/k4a_ros_device.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
k4a_ros_device.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x14c): undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
k4a_ros_device.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x223): undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
k4a_ros_device.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x2b2): undefined reference to `cv::Mat::updateContinuityFlag()'
collect2: error: ld returned 1 exit status
Azure_Kinect_ROS_Driver/CMakeFiles/azure_kinect_ros_driver_node.dir/build.make:213: recipe for target '/home/bgyoo/ros1_ws/devel/lib/azure_kinect_ros_driver/node' failed
make[2]: *** [/home/bgyoo/ros1_ws/devel/lib/azure_kinect_ros_driver/node] Error 1
CMakeFiles/Makefile2:6866: recipe for target 'Azure_Kinect_ROS_Driver/CMakeFiles/azure_kinect_ros_driver_node.dir/all' failed
make[1]: *** [Azure_Kinect_ROS_Driver/CMakeFiles/azure_kinect_ros_driver_node.dir/all] Error 2

This error is opencv version issue, and I know that it requires version 3.4 or higher.
So, I rebuild it with opencv version 3.4 or higher, and it compiles normally, but I get the following warning messages. Is there any problem using it?

> /usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.4.1
/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgproc.so.4.1
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_core.so.4.1

**Comment by tkircher** [comment]
This is a known issue. In order to get this node to work correctly in Melodic you basically have to rebuild both OpenCV and then ROS from source.
