### ISSUE TITLE
When will the ROS 2-dashing version of azure Kinect be released?

### ISSUE THREAD

**Issue by KevinHwangAi** [microsoft/Azure_Kinect_ROS_Driver#129]
Hi Engineers of azure Kinect.

Our team is preparing to use Azure Kinect or Intel D400 series as the main depth camera in our robot project. 
Currently, we want to only use ros2 dashing as the main system tool.
The Kinect does not support dashing but Intel D400 series support.
However,we prefer Kinect . Since last year, we have been looking forward to the support of ROS2-Dashing version from azure Kinect.
Could you tell us when will the ROS 2-dashing version of azure Kinect be released?

**Comment by ooeygui** [comment]
Hello @KevinHwangAi ,
I'd love to know more about your project.
We currently have ROS2 support for all our first party ROS nodes scheduled for June. 

Our plan is to enable the first party nodes for Foxy forward.

**Comment by KevinHwangAi** [comment]
Hi @ooeygui .
Thank you for your answer. We are looking forward to it. 

For our project, we hope to control the robot through Kinect motion capture.

**Comment by ooeygui** [comment]
That sounds like a great project.

Have you investigated using the ROS1 bridge in the mean time?

**Comment by KevinHwangAi** [comment]
Not yet.Maybe we will try later.Thanks.

**Comment by tkircher** [comment]
@KevinHwangAi Our team went with the RealSense D435 + T265 over the Kinect or Zed 2 because of Intel's better support. Still keeping my fingers crossed for the Kinect though, since it's the only real LIDAR camera until the L515 ships.

**Comment by KevinHwangAi** [comment]
@tkircher ,Yes, currently only Kinect provides TOF camera.That's why I want to use Kinect for development.

**Comment by KevinHwangAi** [comment]
Hi @ooeygui.
I am testing the  ros1 bridge to connect Kinect and ros2, but the result is not very satisfactory.The depth image with rviz2 has a large delay,so unable to capture action in real time.

**Comment by ooeygui** [comment]
Working on the Foxy builds now
https://github.com/microsoft/Azure_Kinect_ROS_Driver/pull/155

**Comment by francescosemeraro** [comment]
Good afternoon @ooeygui.
Has there been any progress about the Foxy builds for Azure Kinect? I am trying to make the Azure Kinect ROS Driver in ROS 2, but it is becoming very painful to do it on my own. Having a version easily deployable on ROS 2 could really help me a lot, thanks.

**Comment by ooeygui** [comment]
@francescosemeraro Foxy builds have been committed as part of https://github.com/microsoft/Azure_Kinect_ROS_Driver/pull/155; are you seeing issues with them?
