### ISSUE TITLE
Latest version requires libk4a-1.4 but there are no correspoding libk4abt available for that version

### ISSUE THREAD

**Issue by xiangzhi** [microsoft/Azure_Kinect_ROS_Driver#139]
**Describe the bug**
The latest version requires `libk4a-1.4-dev` to compile. However, Microsoft hasn't release a corresponding body tracking SDK for that version. This means that we can't use any of the body tracking features. More information from the SDK Repo: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1153

**To Reproduce**
1. Try installing `libk4a1.4-dev`. It will automatically uninstall `libk4abt-1.0-dev`
1. Try installing `libk4abt1.0-dev`. You will be asked to install `libk4a1.3-dev` which will fail because we already have `libk4a1.4-dev` installed.
2. When compiling this repo, you will get 
```
Finding K4A SDK binaries
!!! Body Tracking SDK not found: body tracking features will not be available !!!
K4A Libs: k4a::k4a;k4a::k4arecord
K4A DLLs: /usr/lib/x86_64-linux-gnu/libk4a.so.1.4.0;/usr/lib/x86_64-linux-gnu/libk4arecord.so.1.4.0
K4A Install Needed: FALSE

```

**Expected behavior**
Able to use body tracking in the latest version.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Additional context**
This isn't really y'all fault, as it has been a constant request on the main repo. Just wanted to let y'all know that by bumping to 1.4, we will lose body tracking until it is released.

**Comment by ooeygui** [comment]
Had a sync with the Kinect SDK team. The Body tracking SDK was delayed, so I'm backing out https://github.com/microsoft/Azure_Kinect_ROS_Driver/pull/140.
