### ISSUE TITLE
Transforming a (u,v) pixel in the RGB image to (x,y,z) coordinates in the camera frame

### ISSUE THREAD

**Issue by madhan001** [microsoft/Azure_Kinect_ROS_Driver#160]
Hi, my application requires transforming a 2D pixel coordinate in the RGB image to the XYZ values in the camera frame for the robot to reach that point. 

Can anyone please guide me in accomplishing this ?

**Comment by ooeygui** [comment]
Hi @madhan001,
The Camera will publish a [sensor_msgs::pointcloud2](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/PointCloud2.html) on the points2 topic, which reports an XYZRGB in the image relative to the camera frame. The [pcl ROS doc](http://wiki.ros.org/pcl/Overview) is a good starting point for processing the message.
