### ISSUE TITLE
Color stream breaks silently

### ISSUE THREAD

**Issue by jmachowinski** [microsoft/Azure_Kinect_ROS_Driver#181]
**Describe the bug**
On some systems, the color stream breaks down.
This issue is reported in the SDK and the fix will
likely take some time (https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1354).

**To Reproduce**
1. Start the node on any computer using an 'unsupported' usb controler.
   Set 30 fps and color to 2160P
2. rostopic hz /rgb/image_raw
3. Wait some time, hz drops to zero

**Expected behavior**
The node shall crash if the color stream stalls.

The issue here is the 
`if (!k4a_device_.get_capture(&capture, std::chrono::milliseconds(K4A_WAIT_INFINITE)))`
(https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/melodic/src/k4a_ros_device.cpp#L825)
that waits forever in the case that the stream breaks.

I got a tested bugfix and can create a merge request as soon as this issue is approved.

**Comment by ooeygui** [comment]
Agree - waiting infinitely is definitely not desirable.
