### ISSUE TITLE
Asking for human body tracking on recorded rosbag files

### ISSUE THREAD

**Issue by maudzung** [microsoft/Azure_Kinect_ROS_Driver#184]
I have used code in this repository to record data into rosbag files. Are there instructions or examples on loading the recorded rosbag files and doing human body tracking (skeleton extraction)? 

Thank you so much!

**Comment by zchenpds** [comment]
k4abt tracker consumes data of type k4a::capture which cannot be easily reconstructed from the ros messages supplied by this node. Is there any reason you couldn't record the body tracking data into the bag file in the first place? or you want to try the body tracking with different smoothing factor settings on the same data?

This might be related to #122

**Comment by maudzung** [comment]
Thanks for the information. I didn't record `body_tracking_data` topic. I'll record the topic next time for its usage.
