### ISSUE TITLE
How to get timestemp from Azure kinect ROS driver?

### ISSUE THREAD

**Issue by jieunko** [microsoft/Azure_Kinect_ROS_Driver#192]
How to get timestemp from Azure kinect?
It seems there's no topic in kinect ROS driver?

**Comment by ooeygui** [comment]
Which timestamps are you interested in? Is there a specific [REP](https://ros.org/reps/rep-0000.html) you are looking for?
Each camera frame and IMU frame are time stamped.

**Comment by jieunko** [comment]
Oh Now I get it..It is in the Header of the message. Thx..

**Comment by ooeygui** [comment]
Glad I could help :-)
