### ISSUE TITLE
Body Tracking Data - Joint Rotation switching between positive and negative values 

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [microsoft/Azure_Kinect_ROS_Driver#195]
Hi, 
I started the body tracking and then captured the rotation of the pelvis joint and noticed that the data was not consistent.
Can someone kindly let me know why the data of the pelvis joint data obtained from the camera is not consistent with the rotation?  
![image](https://user-images.githubusercontent.com/33458020/120856772-3c19c000-c578-11eb-97d3-999a7ad71aba.png)
Is there a way to fix this?
<arg name="body_tracking_smoothing_factor"  default="1" /> (Does this have any effect?)

Thanks

**Comment by ooeygui** [comment]
@qm13 do you have any input on this?

**Comment by zchenpds** [comment]
This is expected. You converted the quaternion to Euler angles and the yaw angle is wrapped to [-pi, pi), causing the discontinuity you observe in the yaw angle. The quaternion still changes continuously with time.

**Comment by ooeygui** [comment]
@zhenpds Thank you for your input here!
