### ISSUE TITLE
Question about Accessing .mkv files

### ISSUE THREAD

**Issue by wangmiaowei** [microsoft/Azure_Kinect_ROS_Driver#196]
Well, I do not bring my Azure Kinect device now. But I want to process the .mkv file. How can I use the node to access my preoutputted .mkv file and convert it to point cloud?

**Comment by wangmiaowei** [comment]
Well, I do not bring my Azure Kinect device now. But I want to process the .mkv file. How can I use the node to access my preoutputted .mkv file and convert it to point cloud?

**Comment by ooeygui** [comment]
@wangmiaowei The Azure Kinect ROS node does not have this capability. The most accurate way to accomplish what you are looking for is to capture the output from the Azure Kinect to a ROSBag; then you can play it back later as if it came from the camera.

**Comment by zchenpds** [comment]
Thanks to @RoseFlunder, you may play back a .mkv file by starting `driver.launch` with the following argument specified.
https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/cac73214020db1298decb6ad0d22aac45863a531/launch/driver.launch#L39

**Comment by ooeygui** [comment]
@zchenpds Wow, I totally forgot about that. Thank you for responding.

**Comment by wangmiaowei** [comment]
Well, thanks for your suggestion.However, there are some differences with what I have expected. I want a end to end pipeline which  can output point clouds when I play .mkv file in this Azure Kinect ROS system in a real time.
