### ISSUE TITLE
Publish JPEG images instead of BGRA

### ISSUE THREAD

**Issue by skalldri** [microsoft/Azure_Kinect_ROS_Driver#20]
The Azure Kinect does not natively support publishing BGRA images: the BGRA conversion is done in the SDK, with significant processing required on the host to support the conversion.

To reduce the workload on the host device, the ROS node should support publishing a native format (MJPEG is probably a good choice) as well as BGRA format.

**Comment by RoseFlunder** [comment]
Is this the reason why the publishing rate drops significantly when enabling rgb point cloud?
I want to use 30 fps and the rgb point cloud but the publishing rate drops from 30Hz down to 8-12Hz.
