### ISSUE TITLE
Depthcloud and Pointcloud2 not consistent in Rviz

### ISSUE THREAD

**Issue by petpetpeter** [microsoft/Azure_Kinect_ROS_Driver#232]
I'm trying to convert depth image from depth_to_rgb/image_raw topic into pointcloud2
but when I compared it with the PointCloud data in /points2 topic it was a little bit off.
I try checking this problem in RVIZ

![image](https://user-images.githubusercontent.com/55285546/147194923-c356a366-3695-453a-9d05-464392f2feae.png)

The RGB pointcloud is from /points2 topic, the red pointcloud is from /depth_to_rgb/image_raw
Is this normal or some problem? Which one is the more accurate position from the rgb_camera_link?

**Comment by christian-rauch** [comment]
`/points2` is publishing the internally rectified, registered and back-projected data. `/depth_to_rgb/image_raw` publishes the unrectified image. You have to rectify the image, e.g. via [kinect_rgbd.launch](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/melodic/launch/kinect_rgbd.launch).

**Comment by petpetpeter** [comment]
Thanks, I launched the camera with driver.launch, that could be the reason.

**Comment by jiejie567** [comment]
@petpetpeter  Hi, I think /points2 and /depth_to_rgb/image_raw correspond different coordinate system, which is the result there are some drifts.
