### ISSUE TITLE
Synchronize more than three camera

### ISSUE THREAD

**Issue by jieunko** [microsoft/Azure_Kinect_ROS_Driver#239]
I am about to sync 3 or more camera using Daisy-chain configuration.
If I use daisy-chain, camera in the middle suppose to be subordinate for master camera and master for the last camera.
However, there is just one "wired_sync_mode" for ROS_mode parameter to set.
So what should the middle camera's mode in this case?

**Comment by ooeygui** [comment]
I'm sorry, I don't have an answer at the moment. The ROS node currently does not officially support multi-camera setups. 
(There are pass through parameters like the wired sync mode, but they are not tested or documented)

There is a work item to support a multi-camera setup - https://github.com/microsoft/Azure_Kinect_ROS_Driver/issues/126, but this work has not been funded.

**Comment by ooeygui** [comment]
Duplicating to the feature to officially support multi-camera.
https://github.com/microsoft/Azure_Kinect_ROS_Driver/issues/126
