### ISSUE TITLE
Don't register topics that won't be published

### ISSUE THREAD

**Issue by skalldri** [microsoft/Azure_Kinect_ROS_Driver#25]
**Is your feature request related to a problem? Please describe.**
Generally, topics that aren't going to be published given a device configuration, shouldn't be published.

For example, if the `point_cloud` parameter is false, the `points2` topic shouldn't be published.

**Describe the solution you'd like**
Don't publish topics that cannot be provided given a device configuration.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by ooeygui** [comment]
There have been numerous fixes in these code paths which check for subscribers before publishing.
