### ISSUE TITLE
errors when i catkin_make the packages,what should i do?

### ISSUE THREAD

**Issue by working236** [microsoft/Azure_Kinect_ROS_Driver#251]
Base path: /home/nvidia/AzureKinectDriver
Source space: /home/nvidia/AzureKinectDriver/src
Build space: /home/nvidia/AzureKinectDriver/build
Devel space: /home/nvidia/AzureKinectDriver/devel
Install space: /home/nvidia/AzureKinectDriver/install
####
####
####
####
Consolidate compiler generated dependencies of target azure_kinect_ros_driver1_nodelet
Consolidate compiler generated dependencies of target azure_kinect_ros_driver1_node
[ 10%] Linking CXX shared library /home/nvidia/AzureKinectDriver/devel/lib/libazure_kinect_ros_driver1_nodelet.so
[ 20%] Linking CXX executable /home/nvidia/AzureKinectDriver/devel/lib/azure_kinect_ros_driver1/node
[ 60%] Built target azure_kinect_ros_driver1_nodelet
CMakeFiles/azure_kinect_ros_driver1_node.dir/src/k4a_ros_device.cpp.o：在函数‘cv::Mat::Mat(int, int, int, void*, unsigned long)’中：
k4a_ros_device.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x150)：对‘cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)’未定义的引用
k4a_ros_device.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x244)：对‘cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)’未定义的引用
/home/nvidia/CvBridge_ws/devel/lib/libcv_bridge.so：对‘boost::re_detail_106600::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)’未定义的引用
/home/nvidia/CvBridge_ws/devel/lib/libcv_bridge.so：对‘boost::re_detail_106600::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match()’未定义的引用
collect2: error: ld returned 1 exit status
Azure_Kinect_ROS_Driver/CMakeFiles/azure_kinect_ros_driver1_node.dir/build.make:263: recipe for target '/home/nvidia/AzureKinectDriver/devel/lib/azure_kinect_ros_driver1/node' failed
make[2]: *** [/home/nvidia/AzureKinectDriver/devel/lib/azure_kinect_ros_driver1/node] Error 1
CMakeFiles/Makefile2:1739: recipe for target 'Azure_Kinect_ROS_Driver/CMakeFiles/azure_kinect_ros_driver1_node.dir/all' failed
make[1]: *** [Azure_Kinect_ROS_Driver/CMakeFiles/azure_kinect_ros_driver1_node.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by ooeygui** [comment]
Jetson is not currently supported by the ROS driver - https://github.com/microsoft/Azure_Kinect_ROS_Driver/issues/123.
The Nvidia Jetson has released a version of ubuntu in-between 18.04 and 20.04. It uses a new version of OpenCV.
