### ISSUE TITLE
Is it possible to convert 1024x1024 depth image into a 1024x1024x3 point cloud?

### ISSUE THREAD

**Issue by JeffR1992** [microsoft/Azure_Kinect_ROS_Driver#252]
I'm running a series of experiments with the Azure Kinect at a depth resolution of 1024x1024, and am trying to figure out if it's possible to convert a 1024x1024 depth image into an 1024x1024x3 point cloud. That is, I'd like to convert each pixel in the 1024x1024 depth image from an depth/range into an XYZ position.

Alternatively, if the above is not possible, is it possible to convert a PointCloud2 message into a 1024x1024x3 numpy array?

Any help would be appreciated. Thanks!

**Comment by ooeygui** [comment]
Hi there,
You should be able to leverage ros_numpy for converting a pointcloud to numpy - https://pypi.org/project/numpy-ros/.  your python node should subscribe to the depth array and use this python extension to convert.

Good luck!
