### ISSUE TITLE
Question: How to grab images from image topics.

### ISSUE THREAD

**Issue by dpt5216** [microsoft/Azure_Kinect_ROS_Driver#259]
I apologize for the lack of label on this issue (I'm a little bit of a github issue noob)

My university design project teammates and I are attempting to use the Kinect DK to snap pictures for a robotic-arm scanning system. We have the Azure_Kinect_ROS_Driver node working and communicating with another machine over wifi and can see semi-live images through rviz. But we don't know how to actually save those images. 

Is there a recommended way to grab the most recent image off say the `rgb/image_raw` topic from another node and save it to a file?

**Comment by ooeygui** [comment]
Sorry for the delay in responding. You didn't mention which ROS distro or platform you were using. However, there is an image_view tool on ROS1 which can do this for you - http://wiki.ros.org/image_view. (It has a ROS2 port, but I haven't tried it)

I hope that helps!
