### ISSUE TITLE
Driver launch file ignores sensor serial number

### ISSUE THREAD

**Issue by aravindbattaje** [microsoft/Azure_Kinect_ROS_Driver#47]
The sensor serial number parameter `sensor_sn` is ignored in the `driver.launch`. 

The fix is to add the parameter in the launch file, as in https://github.com/aravindbattaje/Azure_Kinect_ROS_Driver/commit/3a1856043316a45a6b12f0680d087f80e088d2ad . (Will create PR when triage approved.)

**Comment by skalldri** [comment]
Approved: thanks for the fix!

**Comment by skalldri** [comment]
Fixed by #48
