### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by skalldri** [microsoft/Azure_Kinect_ROS_Driver#5]
As ROS1 is slowly being phased out in favor of ROS2, we should begin to investigate supporting ROS2 with Azure Kinect. This will involve creating a new branch to support a ROS2 release, and then porting the node to run on the new ROS2 messaging stack.

**Comment by ooeygui** [comment]
https://github.com/microsoft/Azure_Kinect_ROS_Driver/pull/155
