### ISSUE TITLE
Formatting the code with clang-format to apply ROS CppStyleGuide

### ISSUE THREAD

**Issue by RoseFlunder** [microsoft/Azure_Kinect_ROS_Driver#53]
**Is your feature request related to a problem? Please describe.**
In one of my pull requests I forgot some indentation in the code.
There exists a [ROS CppStyleGuide](http://wiki.ros.org/CppStyleGuide) which we could apply to this codebase.
For autoformatting they provide a .clang-format file:
[https://github.com/davetcoleman/roscpp_code_format](https://github.com/davetcoleman/roscpp_code_format)

I saw that the [Azure-Kinect-Sensor-SDK](https://github.com/microsoft/Azure-Kinect-Sensor-SDK) also has a .clang-format file in its repository and its consumed in the CMakeLists.txt:
[https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CMakeLists.txt#L147](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CMakeLists.txt#L147)

I don't really know this is just some temporaray formatting for the build process or if the source files actually are formatted after this. I never tried this out yet together with CMake. I only used the format file manually in my VS Code Editor.
If all files are formatted after the build it would be a good improvement because every pull request should invoke building the package -> all files would be formatted automatically.

**Describe the solution you'd like**
Integrate the .clang-format file and use it during the CMake build process.
Ensure correct formatting.

**Describe alternatives you've considered**
Semi manual formatting the code calling clang format after changing source file.

**Comment by skalldri** [comment]
Agreed, we should be using Clang format where possible, though I don't 100% agree with the entire ROS CPP style guide. I'll investigate adding a Clang format file that matches this repo's style.
