### ISSUE TITLE
Getting an error on catkin_make: configuration file not accepted

### ISSUE THREAD

**Issue by amamamahmood** [microsoft/Azure_Kinect_ROS_Driver#71]
Hello,

I have installed Microsoft Kinect Azure SDK on ubuntu 18.04 When I try to build this repo, I get this error on running "catkin_make"

Kindly help me with it

![issue](https://user-images.githubusercontent.com/45050422/64646819-cc4bc500-d3e5-11e9-8ea3-21eda637fee9.png)

**Comment by skalldri** [comment]
You need to update to the [1.2.0 Azure Kinect SDK](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md).

**Comment by amamamahmood** [comment]
I try doing it using: 
sudo apt install libk4a1.2-dev
But I get this error:
![issue2](https://user-images.githubusercontent.com/45050422/64647350-da4e1580-d3e6-11e9-868a-981d8cb0f465.png)

Do I need to get rid of libk4a1.1.1 first? If yes, How?

**Comment by skalldri** [comment]
Yes, you need to uninstall the old Azure Kinect SDK first.

`sudo apt purge libk4a1.1-dev libk4a1.1` should remove all traces of the
old SDK.
