### ISSUE TITLE
Publish body index map in ROS

### ISSUE THREAD

**Issue by zchenpds** [microsoft/Azure_Kinect_ROS_Driver#75]
**Is your feature request related to a problem? Please describe.**
No body segmentation result is provided by this driver.

**Describe the solution you'd like**
Publish [body index map](https://docs.microsoft.com/en-us/azure/Kinect-dk/body-index-map) in ROS if `body_tracking_enabled=true`

**Describe alternatives you've considered**
(None)

**Additional context**
![](https://docs.microsoft.com/en-us/azure/Kinect-dk/media/concepts/body-index-map.png)

**Comment by RoseFlunder** [comment]
@zchenpds 
I just created a pull request which adds a topic for the body index map.
You could test if this meets your requirements.

**Comment by zchenpds** [comment]
@RoseFlunder 
Thanks a lot for creating the pull request. I should have made it clearer in the **Additional Context** that I wanted to use the index map to find from the depth image a group of points corresponding to a particular body segment of a particular body. Although an RGB index map is visually pleasing, it's costlier to query from an RGB index map whether a depth image pixel belongs to a particular body. Are there any other reasons that you prefer RGB over a mono image?

**Comment by RoseFlunder** [comment]
This was just my initial idea to have the same color as the body markers for the joints have and you provided an example RGB image in the additional context :D
But I have no problem in changing it up.
I can change it a mono8 image.
What about the values? Body IDs & 255 as background?
I think body IDs make more sense than just the raw index to have a relation to the markers?
What do you think?
But I guess we would have to use body ID mod 255 then to get no possibe overflow and mix up with the background.

@zchenpds
I changed it to MONO8 as described. Any further suggestions?

**Comment by zchenpds** [comment]
Sorry for the confusion. Thanks again for your help.

**Comment by RoseFlunder** [comment]
No problem. I am glad to help.
You can try the updated pull request again and give feedback if this matches your requirements now.

EDIT: Just pushed a tiny fix for a typo that sneaked in before.

**Comment by skalldri** [comment]
Fixed by #81
