### ISSUE TITLE
Add a new parameter to control the body tracking smoothing between frames

### ISSUE THREAD

**Issue by RoseFlunder** [microsoft/Azure_Kinect_ROS_Driver#79]
**Is your feature request related to a problem? Please describe.**
Since body tracking SDK version 0.9.2 there is a method to set the smoothing factor between 0 (no smoothing) and 1 (full smoothing). The default is 0.0 since 0.9.3 and it should be possible to change this value for the node.

**Describe the solution you'd like**
Add a parameter for the node to override the default value of 0.0.

**Comment by skalldri** [comment]
Fixed by #80
