### ISSUE TITLE
Is it ok to remove `joint_state_publisher` in `driver.launch` file?

### ISSUE THREAD

**Issue by msr-peng** [microsoft/Azure_Kinect_ROS_Driver#95]
Just as the title.

Currently when launch `driver.launch`, it will default start `joint_state_publisher` node which publish topic `joint_state` (actually its message has nothing). When I incorporated Azure Kinect into my robot, it will conflict with my robot built-in `joint_state` topic. So is it ok to remove `joint_state_publisher` node in `driver.launch` file ([this line](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/3a41786f4aa96ee3a7178b7888923dd5ffdf0113/launch/driver.launch#L12))?

**Comment by ooeygui** [comment]
This is now implemented.
